name: Docker Compose Test and Check

on: [ push, pull_request ]

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker Compose
        run: docker-compose up --build -d

      - name: Check MySQL Container
        run: docker container inspect mysql-container --format '{{.State.Health.Status}}' | grep healthy

      - name: Check PHPMyAdmin Container
        run: docker container inspect phpmyadmin-container --format '{{.State.Running}}' | grep true

      - name: Tear down Docker Compose
        run: docker-compose down

      - name: Remove Docker Compose Containers and Networks
        run: docker container prune -f